### ISSUE TITLE
Is `pi_camera_reg_set16` correctly implemented?

### ISSUE THREAD

**Issue by zeroos** [jeguzzi/ai_sail#1]
Hey!

I was browsing through this project (btw., really cool stuff!) hoping it'll help me figure out how to force a specific exposure setting on himax in my code. While doing that, I've seen that in `pi_camera_reg_set16` function (which, as I understand, should be setting a parameter):

https://github.com/jeguzzi/ai_sail/blob/0c6894f6db4c22aad3836b80f3e2470c88729d26/gap/streamer/himax_utils.c#L146

the low byte is being set, but for the high one, the *get* function is being used. Am I missing something or it's a mistake?

**Comment by jeguzzi** [comment]
It's a mistake. Thanks for pointing it out.

**Comment by jeguzzi** [comment]
Fixed in https://github.com/jeguzzi/ai_sail/commit/71610d74ae70ff776c85cb84ada46e2bf37a8382

**Comment by zeroos** [comment]
Thanks for the clarification, makes sense! So I guess the three lines here: https://github.com/jeguzzi/ai_sail/blob/master/gap/streamer/himax_utils.c#L419 were not really tested? In my tests, it seems like they are not really changing anything, but I understand that they should. I've created an issue on bitcraze's github about this: https://github.com/bitcraze/AIdeck_examples/issues/60 , maybe you also have some insights?

**Comment by jeguzzi** [comment]
The lines are executed if/when autoexposure is turned off after the first (10 by default) frames are acquired. 
I suppose that by chance the most significant byte does not change during this calibration procedure (when the mean is computed over the 10 frames) so the mistake you found played no role.

**Comment by zeroos** [comment]
I missed the part that they are executed only once, but still, in my experiments, it seems these parameters are not changing anything... I guess I just need to investigate further, thanks for the comment!
